version: '3.8'

services:
  db:
    image: postgres:15-alpine # Using PostgreSQL 15
    volumes:
      - postgres_data:/var/lib/postgresql/data/ # Persistent data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres} # Default to 'postgres' if not in .env
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme} # Default, change in .env
      - POSTGRES_DB=${POSTGRES_DB:-appdb} # Default, change in .env
    ports:
      - "${POSTGRES_PORT:-5432}:5432" # Expose port, configurable via .env
    networks:
      - app-network
    restart: unless-stopped
    healthcheck: # Added healthcheck for PostgreSQL
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-postgres} -d $${POSTGRES_DB:-appdb} -q"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s # Give it some time to start before first check

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    # env_file: # We can use environment block instead for more clarity with defaults
    #   - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-changeme}@db:5432/${POSTGRES_DB:-appdb}
      - OKTA_ISSUER=${OKTA_ISSUER}
      - OKTA_CLIENT_ID=${OKTA_CLIENT_ID}
      # Add any other backend specific env vars here
    volumes:
      - ./app:/app
    depends_on:
      db: # Backend depends on the PostgreSQL database
        condition: service_healthy # Optional: wait for DB to be healthy (requires healthcheck in db service)
    networks:
      - app-network
    # Healthcheck for backend (optional, example)
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8000/api/public"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_OKTA_ISSUER=${OKTA_ISSUER}
      - REACT_APP_OKTA_CLIENT_ID=${OKTA_CLIENT_ID}
      - REACT_APP_OKTA_CLIENT_SECRET=${OKTA_CLIENT_SECRET} # Still here if frontend might use it later, otherwise remove
      - REACT_APP_API_URL=http://localhost:8000 # This will be http://backend:8000 if services communicate over Docker network by service name
    volumes:
      - ./client:/app
      - /app/node_modules 
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: # Define the named volume for data persistence 