FROM python:3.11-slim

WORKDIR /app

# Add the parent directory of 'app' to PYTHONPATH
ENV PYTHONPATH "${PYTHONPATH}:/"

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./app .

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"] 